import 'dotenv/config'
import cors from 'cors'
import express from 'express'
import { prisma } from '../src/server/prisma'
import { getDashboardData } from '../src/server/services/dashboardService'
import { assignmentData, clubEventData, courseData, getCourses, getCurrentSemester } from '../src/server/services/semesterService'

const app = express(); app.use(cors()); app.use(express.json())
const port = Number(process.env.API_PORT ?? 3001)
const getUserId = async (value?: string) => value ?? (await prisma.user.findUnique({ where: { email: 'tom.sullivan@example.com' } }))?.id

app.get('/api/dashboard', async (request, response) => { try { const userId = await getUserId(request.query.userId as string); if (!userId) return response.status(404).json({ error: 'Demo user not found. Run the seed first.' }); return response.json(await getDashboardData(userId)) } catch (error) { return response.status(500).json({ error: error instanceof Error ? error.message : 'Unable to load dashboard' }) } })
app.get('/api/semesters/current', async (request, response) => { const userId = await getUserId(request.query.userId as string); if (!userId) return response.status(404).json({ error: 'User not found' }); return response.json(await getCurrentSemester(userId)) })
app.get('/api/courses', async (request, response) => response.json(await getCourses(request.query.semesterId as string)))
app.get('/api/semester-data', async (request, response) => { const userId = await getUserId(request.query.userId as string); if (!userId) return response.status(404).json({ error: 'User not found' }); const semester = await prisma.semester.findFirst({ where: { userId, isCurrent: true }, include: { courses: { include: { meetings: true, assignments: { orderBy: { dueDate: 'asc' } }, exams: { orderBy: { examDate: 'asc' } } } } } }); const clubs = await prisma.club.findMany({ where: { userId }, include: { events: { orderBy: { startDate: 'asc' } } }, orderBy: { name: 'asc' } }); const personalEvents = await prisma.calendarEvent.findMany({ where: { userId, kind: 'PERSONAL' }, orderBy: { startDate: 'asc' } }); if (!semester) return response.status(404).json({ error: 'Current semester not found' }); return response.json({ semester, clubs, personalEvents }) })
app.post('/api/courses', async (request, response) => response.status(201).json(await prisma.course.create({ data: courseData(request.body) })))
app.patch('/api/courses/:id', async (request, response) => response.json(await prisma.course.update({ where: { id: request.params.id }, data: request.body })))
app.delete('/api/courses/:id', async (request, response) => { await prisma.course.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.post('/api/class-meetings', async (request, response) => response.status(201).json(await prisma.classMeeting.create({ data: request.body })))
app.patch('/api/class-meetings/:id', async (request, response) => response.json(await prisma.classMeeting.update({ where: { id: request.params.id }, data: request.body })))
app.delete('/api/class-meetings/:id', async (request, response) => { await prisma.classMeeting.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.post('/api/calendar-classes', async (request, response) => { try { const userId = await getUserId(request.body.userId); if (!userId) return response.status(404).json({ error: 'User not found' }); const semester = await prisma.semester.findFirst({ where: { id: request.body.semesterId, userId, isCurrent: true } }); if (!semester) return response.status(404).json({ error: 'Current semester not found' }); const days = Array.isArray(request.body.daysOfWeek) ? request.body.daysOfWeek.map(Number).filter((day: number) => day >= 1 && day <= 5) : []; if (!days.length) return response.status(400).json({ error: 'Select at least one weekday' }); if (!request.body.startTime || !request.body.endTime || request.body.endTime <= request.body.startTime) return response.status(400).json({ error: 'End time must be after start time' }); const startDate = new Date(request.body.startDate); const endDate = new Date(request.body.endDate); if (Number.isNaN(startDate.getTime()) || Number.isNaN(endDate.getTime()) || endDate < startDate) return response.status(400).json({ error: 'End date must be on or after start date' }); const result = await prisma.$transaction(async transaction => { const course = request.body.courseId === 'OTHER' ? await transaction.course.create({ data: { semesterId: semester.id, courseCode: request.body.courseCode, name: request.body.customCourseName, building: request.body.building, room: request.body.room } }) : await transaction.course.findFirst({ where: { id: request.body.courseId, semesterId: semester.id } }); if (!course) throw new Error('Select a valid course'); if (!course.name || (request.body.courseId === 'OTHER' && !request.body.customCourseName?.trim())) throw new Error('Enter a custom course name'); return transaction.classMeeting.createMany({ data: days.map((dayOfWeek: number) => ({ courseId: course.id, dayOfWeek, startDate, endDate, startTime: request.body.startTime, endTime: request.body.endTime, building: request.body.building || course.building, room: request.body.room || course.room })) }) }); return response.status(201).json(result) } catch (error) { return response.status(400).json({ error: error instanceof Error ? error.message : 'Unable to create class' }) } })
app.post('/api/calendar-events', async (request, response) => { const userId = await getUserId(request.body.userId); if (!userId) return response.status(404).json({ error: 'User not found' }); if (request.body.kind !== 'PERSONAL') return response.status(400).json({ error: 'Only personal calendar events use this endpoint' }); return response.status(201).json(await prisma.calendarEvent.create({ data: { userId, kind: 'PERSONAL', title: request.body.title, startDate: new Date(request.body.startDate), endDate: new Date(request.body.endDate), location: request.body.location } })) })
app.delete('/api/calendar-events/:id', async (request, response) => { await prisma.calendarEvent.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.post('/api/assignments', async (request, response) => response.status(201).json(await prisma.assignment.create({ data: assignmentData({ ...request.body, dueDate: new Date(request.body.dueDate) }) })))
app.get('/api/assignments', async (request, response) => { const courseId = request.query.courseId as string | undefined; const semesterId = request.query.semesterId as string | undefined; return response.json(await prisma.assignment.findMany({ where: courseId ? { courseId } : { course: { semesterId } }, include: { course: true }, orderBy: { dueDate: 'asc' } })) })
app.patch('/api/assignments/:id', async (request, response) => response.json(await prisma.assignment.update({ where: { id: request.params.id }, data: request.body })))
app.delete('/api/assignments/:id', async (request, response) => { await prisma.assignment.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.post('/api/exams', async (request, response) => response.status(201).json(await prisma.exam.create({ data: { ...request.body, examDate: new Date(request.body.examDate) } })))
app.delete('/api/exams/:id', async (request, response) => { await prisma.exam.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.post('/api/club-events', async (request, response) => response.status(201).json(await prisma.clubEvent.create({ data: clubEventData({ ...request.body, startDate: new Date(request.body.startDate), endDate: new Date(request.body.endDate) }) })))
app.get('/api/club-events', async (request, response) => response.json(await prisma.clubEvent.findMany({ where: { clubId: request.query.clubId as string }, include: { club: true }, orderBy: { startDate: 'asc' } })))
app.patch('/api/club-events/:id', async (request, response) => response.json(await prisma.clubEvent.update({ where: { id: request.params.id }, data: request.body })))
app.delete('/api/club-events/:id', async (request, response) => { await prisma.clubEvent.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.get('/api/clubs', async (request, response) => response.json(await prisma.club.findMany({ where: { userId: request.query.userId as string | undefined }, include: { events: { orderBy: { startDate: 'asc' } } }, orderBy: { name: 'asc' } })))
app.post('/api/clubs', async (request, response) => { const userId = await getUserId(request.body.userId); if (!userId) return response.status(404).json({ error: 'User not found' }); return response.status(201).json(await prisma.club.create({ data: { ...request.body, userId } })) })
app.patch('/api/clubs/:id', async (request, response) => response.json(await prisma.club.update({ where: { id: request.params.id }, data: request.body })))
app.delete('/api/clubs/:id', async (request, response) => { await prisma.club.delete({ where: { id: request.params.id } }); return response.status(204).send() })
app.listen(port, () => console.log(`SemesterHub API listening on http://localhost:${port}`))
