const base = import.meta.env.VITE_API_URL ?? 'http://localhost:3001'
export async function api<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(`${base}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error ?? 'Request failed') }; return response.status === 204 ? undefined as T : response.json() }
export const appData = () => api<any>('/api/semester-data')
export const allAssignments = (semesterId: string) => api<any[]>(`/api/assignments?semesterId=${semesterId}`)
export const saveAssignment = (body: unknown, id?: string) => api<any>(id ? `/api/assignments/${id}` : '/api/assignments', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) })
export const removeAssignment = (id: string) => api<void>(`/api/assignments/${id}`, { method: 'DELETE' })
export const saveCourse = (body: unknown, id?: string) => api<any>(id ? `/api/courses/${id}` : '/api/courses', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) })
export const removeCourse = (id: string) => api<void>(`/api/courses/${id}`, { method: 'DELETE' })
export const saveMeeting = (body: unknown, id?: string) => api<any>(id ? `/api/class-meetings/${id}` : '/api/class-meetings', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) })
export const createCalendarClass = (body: unknown) => api<{ count: number }>('/api/calendar-classes', { method: 'POST', body: JSON.stringify(body) })
export const removeMeeting = (id: string) => api<void>(`/api/class-meetings/${id}`, { method: 'DELETE' })
export const saveClub = (body: unknown, id?: string) => api<any>(id ? `/api/clubs/${id}` : '/api/clubs', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) })
export const removeClub = (id: string) => api<void>(`/api/clubs/${id}`, { method: 'DELETE' })
export const saveEvent = (body: unknown, id?: string) => api<any>(id ? `/api/club-events/${id}` : '/api/club-events', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) })
export const removeEvent = (id: string) => api<void>(`/api/club-events/${id}`, { method: 'DELETE' })
export const saveCalendarEvent = (body: unknown) => api<any>('/api/calendar-events', { method: 'POST', body: JSON.stringify(body) })
export const removeCalendarEvent = (id: string) => api<void>(`/api/calendar-events/${id}`, { method: 'DELETE' })
export const saveExam = (body: unknown) => api<any>('/api/exams', { method: 'POST', body: JSON.stringify(body) })
export const removeExam = (id: string) => api<void>(`/api/exams/${id}`, { method: 'DELETE' })
