import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react'
import { appData } from '../api/appApi'

type Kind = 'class' | 'assignment' | 'exam' | 'club'
type CalendarItem = { id: string; title: string; detail: string; date: Date; kind: Kind; time?: string }
type Data = Awaited<ReturnType<typeof appData>>
const labels: Record<Kind, string> = { class: 'Classes', assignment: 'Assignments', exam: 'Exams', club: 'Club events' }
const colors: Record<Kind, string> = { class: 'blue', assignment: 'orange', exam: 'red', club: 'purple' }
const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const startOfWeek = (date: Date) => { const next = new Date(date); next.setDate(next.getDate() - next.getDay()); next.setHours(0, 0, 0, 0); return next }
const sameDay = (left: Date, right: Date) => left.toDateString() === right.toDateString()
function CalendarShell({ children, onHome }: { children: ReactNode; onHome: () => void }) { return <main className="page-shell"><button className="back-link" onClick={onHome}><ChevronLeft size={16}/> Home</button><div className="page-heading"><span className="eyebrow">SEMESTERHUB · FALL 2026</span><h1>Calendar</h1><p>Classes, deadlines, exams, and events in one place.</p></div>{children}</main> }
export function CalendarLayout({ onHome }: { onHome: () => void }) {
  const [data, setData] = useState<Data | null>(null); const [view, setView] = useState<'month' | 'week' | 'day'>('month'); const [cursor, setCursor] = useState(new Date()); const [filters, setFilters] = useState<Record<Kind, boolean>>(() => JSON.parse(localStorage.getItem('semesterhub-calendar-filters') ?? '{"class":true,"assignment":true,"exam":true,"club":true}'))
  useEffect(() => { appData().then(setData) }, [])
  const items = useMemo<CalendarItem[]>(() => { if (!data) return []; const result: CalendarItem[] = []; data.semester.courses.forEach((course: any) => { course.meetings.forEach((meeting: any) => { for (let offset = -35; offset <= 35; offset++) { const date = new Date(cursor); date.setDate(cursor.getDate() + offset); if ((date.getDay() || 7) === meeting.dayOfWeek) result.push({ id: `${meeting.id}-${date.toISOString().slice(0, 10)}`, title: course.courseCode, detail: course.name, date, time: meeting.startTime, kind: 'class' }) } }); course.assignments.forEach((item: any) => result.push({ id: item.id, title: item.title, detail: course.courseCode, date: new Date(item.dueDate), time: item.dueTime, kind: 'assignment' })); course.exams.forEach((item: any) => result.push({ id: item.id, title: item.title, detail: course.courseCode, date: new Date(item.examDate), time: item.startTime, kind: 'exam' })) }); data.clubs.forEach((club: any) => club.events.forEach((item: any) => result.push({ id: item.id, title: item.name, detail: club.name, date: new Date(item.startDate), time: new Date(item.startDate).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }), kind: 'club' }))); return result.filter(item => filters[item.kind]) }, [data, cursor, filters])
  const toggle = (kind: Kind) => { const next = { ...filters, [kind]: !filters[kind] }; setFilters(next); localStorage.setItem('semesterhub-calendar-filters', JSON.stringify(next)) }
  const move = (amount: number) => { const next = new Date(cursor); next.setDate(next.getDate() + (view === 'month' ? amount * 30 : view === 'week' ? amount * 7 : amount)); setCursor(next) }
  const week = startOfWeek(cursor); const weekDays = Array.from({ length: 7 }, (_, index) => { const date = new Date(week); date.setDate(week.getDate() + index); return date }); const monthStart = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const gridStart = new Date(monthStart); gridStart.setDate(1 - monthStart.getDay()); const monthDays = Array.from({ length: 42 }, (_, index) => { const date = new Date(gridStart); date.setDate(gridStart.getDate() + index); return date }); const visible = (date: Date) => items.filter(item => sameDay(item.date, date)).sort((a, b) => (a.time ?? '').localeCompare(b.time ?? ''))
  if (!data) return <CalendarShell onHome={onHome}><div className="data-state">Loading calendar...</div></CalendarShell>
  return <CalendarShell onHome={onHome}><div className="calendar-toolbar"><button className="icon-btn" onClick={() => move(-1)} aria-label="Previous period"><ChevronLeft/></button><strong>{view === 'day' ? cursor.toLocaleDateString() : cursor.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</strong><button className="icon-btn" onClick={() => move(1)} aria-label="Next period"><ChevronRight/></button><span className="calendar-views">{(['month','week','day'] as const).map(option => <button className={view === option ? 'filter active' : 'filter'} key={option} onClick={() => setView(option)}>{option[0].toUpperCase() + option.slice(1)}</button>)}</span></div><div className="calendar-filters">{(Object.keys(labels) as Kind[]).map(kind => <label key={kind}><input type="checkbox" checked={filters[kind]} onChange={() => toggle(kind)}/><i className={`filter-dot ${colors[kind]}`}/>{labels[kind]}</label>)}</div>{view === 'month' && <div className="content-card calendar-card calendar-layout"><div className="calendar-grid">{dayNames.map(day => <strong key={day}>{day}</strong>)}{monthDays.map(date => <div className={`calendar-cell ${date.getMonth() !== cursor.getMonth() ? 'muted-day' : ''}`} key={date.toISOString()}><span>{date.getDate()}</span>{visible(date).slice(0, 3).map(item => <b className={`calendar-event ${item.kind}`} title={`${item.title} · ${item.detail}`} key={item.id}>{item.title}</b>)}{visible(date).length > 3 && <small>+{visible(date).length - 3} more</small>}</div>)}</div></div>}{view === 'week' && <div className="content-card calendar-week-layout">{weekDays.map(date => <div className="calendar-day-column" key={date.toISOString()}><header><span>{dayNames[date.getDay()]}</span><strong>{date.getDate()}</strong></header>{visible(date).map(item => <div className={`calendar-timeline-event ${item.kind}`} key={item.id}><b>{item.time ?? 'All day'}</b><strong>{item.title}</strong><small>{item.detail}</small></div>)}{visible(date).length === 0 && <span className="calendar-empty">Nothing scheduled</span>}</div>)}</div>}{view === 'day' && <div className="content-card day-agenda"><div className="day-agenda-heading"><CalendarDays size={18}/><strong>{cursor.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</strong></div>{visible(cursor).map(item => <div className={`calendar-result ${item.kind}`} key={item.id}><span className={`calendar-result-mark ${colors[item.kind]}`}><CalendarDays size={14}/></span><div><strong>{item.title}</strong><small>{item.time ?? 'All day'} · {item.detail}</small></div><span className="result-type">{labels[item.kind]}</span></div>)}{visible(cursor).length === 0 && <div className="empty-panel">Nothing scheduled.</div>}</div>}</CalendarShell>
}

