import { useEffect, useState } from 'react'
import { Bell, CalendarDays, ChevronDown, CircleHelp, Clock3, FileText, GraduationCap, LayoutDashboard, MapPin, Menu, MoreHorizontal, NotebookPen, Plus, Search, Settings, Sparkles, Users, X } from 'lucide-react'
import { fetchDashboard, toAssignments, toEvents, toScheduleItems, type DashboardData } from '../api/dashboardApi'
import { navItems } from '../data/navigation'
import type { Assignment, ClubEvent, ScheduleItem, Tone } from '../data/dashboardTypes'

const icons = [LayoutDashboard, GraduationCap, FileText, CalendarDays, Clock3, Users, NotebookPen, NotebookPen, Settings]
const toneClass = (tone: Tone) => `tone-${tone}`

function Header({ onMenu, search, onSearch, onAction, onNavigate }: { onMenu: () => void; search: string; onSearch: (value: string) => void; onAction: (message: string) => void; onNavigate?: (item: string) => void }) {
  return <header className="topbar"><button className="mobile-menu icon-btn" onClick={onMenu} aria-label="Open menu"><Menu size={20} /></button><button className="brand" onClick={() => onNavigate?.('Home')}><span className="brand-mark"><Sparkles size={17} /></span><span>semester<span>hub</span></span></button><div className="search"><Search size={18} /><input value={search} onChange={event => onSearch(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && search.trim()) onNavigate?.(`Search:${search.trim()}`) }} placeholder="Search anything..." aria-label="Search" /><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-btn" onClick={() => onAction('Help center coming soon')} aria-label="Help"><CircleHelp size={19} /></button><button className="icon-btn has-dot" onClick={() => onAction('You have 3 new notifications')} aria-label="Notifications"><Bell size={19} /></button><button className="icon-btn" onClick={() => onNavigate?.('Calendar')} aria-label="Calendar"><CalendarDays size={19} /></button><div className="avatar small">TS</div><button className="semester-select" onClick={() => onAction('Semester switching will be available soon')}>Fall 2024 <ChevronDown size={15} /></button></div></header>
}

function Sidebar({ open, active, onSelect, close, onAction }: { open: boolean; active: string; onSelect: (item: string) => void; close: () => void; onAction: (message: string) => void }) {
  return <><aside className={`sidebar ${open ? 'open' : ''}`}><div className="profile"><div className="avatar">TS</div><div><strong>Tom Sullivan</strong><span>Computer Science</span></div><button className="icon-btn" onClick={() => onAction('Profile menu coming soon')} aria-label="Open profile menu"><MoreHorizontal size={17} /></button></div><nav>{navItems.map((item, i) => { const Icon = icons[i]; return <button key={item} className={active === item ? 'active' : ''} onClick={() => { onSelect(item); close() }}><Icon size={18} /><span>{item}</span>{item === 'Assignments' && <em>3</em>}</button> })}</nav><div className="sidebar-bottom"><div className="semester-card"><div className="mini-label">CURRENT SEMESTER</div><strong>Fall 2024</strong><span>Aug 26 - Dec 13, 2024</span><div className="progress"><i /></div><small>Week 8 of 16 <b>50%</b></small></div><button className="sidebar-help" onClick={() => onAction('Help center coming soon')}><div className="help-icon"><CircleHelp size={17} /></div><span><strong>Need a hand?</strong><small>Visit our help center</small></span><ChevronDown size={15} /></button></div></aside>{open && <button className="scrim" onClick={close} aria-label="Close menu"><X size={1} /></button>}</>
}

function SectionHeader({ title, action }: { title: string; action?: string }) { return <div className="section-heading"><h2>{title}</h2>{action && <button className="text-btn">{action} <span>→</span></button>}</div> }
function StatCard({ label, value, caption, tone, icon: Icon }: { label: string; value: string; caption: string; tone: Tone; icon: typeof Clock3 }) { return <div className="stat-card"><div className={`stat-icon ${toneClass(tone)}`}><Icon size={18} /></div><div><span>{label}</span><strong>{value}</strong><small className={tone === 'red' ? 'danger' : ''}>{caption}</small></div><button className="card-more"><MoreHorizontal size={17} /></button></div> }

function Schedule({ query, items }: { query: string; items: ScheduleItem[] }) { const filtered = items.filter(item => `${item.course} ${item.name} ${item.room}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel schedule-panel"><SectionHeader title="Today's Schedule" action="View calendar" /><div className="schedule-list">{filtered.length ? filtered.map((item, i) => <div className={`schedule-row ${i === 0 ? 'current' : ''}`} key={item.course}><div className="schedule-time"><strong>{item.time}</strong><span>{item.endTime}</span></div><div className={`course-dot ${toneClass(item.tone)}`} /><div className="schedule-info"><strong>{item.course} <span>{item.name}</span></strong><small><MapPin size={13} />{item.room}</small></div><span className={i === 0 ? 'until now' : 'until'}>{item.until}</span></div>) : <p className="empty-state">{query ? `No classes match “${query}”.` : 'No classes scheduled today.'}</p>}</div></section> }
function Assignments({ query, items }: { query: string; items: Assignment[] }) { const filtered = items.filter(item => `${item.course} ${item.title} ${item.due}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel compact-panel"><SectionHeader title="Upcoming Assignments" action="See all" /><div className="assignment-list">{filtered.length ? filtered.map(item => <div className="assignment-row" key={item.title}><div className={`course-badge ${toneClass(item.tone)}`}>{item.course.split(' ')[0]}</div><div className="row-copy"><strong>{item.title}</strong><small>{item.course} · <span className={item.priority === 'High' ? 'danger' : ''}>{item.due}</span></small></div><span className={`priority ${toneClass(item.tone)}`}>{item.priority}</span></div>) : <p className="empty-state">{query ? `No assignments match “${query}”.` : 'No upcoming assignments.'}</p>}</div></section> }
function Events({ query, items, onAction }: { query: string; items: ClubEvent[]; onAction: (message: string) => void }) { const filtered = items.filter(item => `${item.club} ${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel compact-panel"><SectionHeader title="Upcoming Club Events" action="See all" /><div className="event-list">{filtered.length ? filtered.map(item => <div className="event-row" key={item.title}><div className={`event-date ${toneClass(item.tone)}`}><strong>{item.date.split(' ')[0]}</strong><span>{item.date.split(' ')[1]?.replace('·', '')}</span></div><div className="row-copy"><strong>{item.title}</strong><small>{item.club} · {item.location}</small></div><button className="add-btn" onClick={() => onAction(`${item.title} added to your calendar`)} aria-label={`Add ${item.title} to calendar`}><Plus size={17} /></button></div>) : <p className="empty-state">{query ? `No events match “${query}”.` : 'No upcoming events.'}</p>}</div></section> }
function WeekGlance() { return <section className="panel week-panel"><SectionHeader title="Week at a Glance" action="Full calendar" /><div className="week-days">{['Mon 14', 'Tue 15', 'Wed 16', 'Thu 17', 'Fri 18', 'Sat 19', 'Sun 20'].map((day, i) => <div className={i === 1 ? 'today' : ''} key={day}><span>{day.split(' ')[0]}</span><strong>{day.split(' ')[1]}</strong></div>)}</div><div className="week-grid">{[['9 AM','CS 301'],['10 AM',''],['11 AM','MATH 214'],['12 PM',''],['1 PM',''],['2 PM','ENG 205'],['3 PM','']].map(([time, label], i) => <div className="week-line" key={time}><span>{time}</span><div>{label && <b className={`week-event ${i === 2 ? 'purple' : i === 5 ? 'orange' : ''}`}>{label}</b>}</div></div>)}</div></section> }
function RightRail() { return <aside className="right-rail"><section className="rail-panel next-up"><SectionHeader title="Next Up" /><div className="next-course"><div className="course-badge tone-blue">CS</div><div><strong>Data Structures & Algorithms</strong><span>9:00 AM · Science Hall 204</span></div><span className="live-dot" /></div><button className="outline-btn">Open class details <span>→</span></button></section><section className="rail-panel"><SectionHeader title="This Week Overview" /><div className="overview"><div><strong>12</strong><span>classes</span></div><div><strong>7</strong><span>assignments</span></div><div><strong>2</strong><span>events</span></div></div><div className="week-progress"><span><b>Week 8</b> of 16</span><strong>50%</strong><div><i /></div></div></section><section className="rail-panel deadlines"><SectionHeader title="Deadlines" action="View all" /><div className="deadline"><span className="deadline-date red-text">TODAY</span><strong>Problem Set 4: Graphs</strong><small>CS 301 · 11:59 PM</small></div><div className="deadline"><span className="deadline-date orange-text">TOMORROW</span><strong>Proof Portfolio</strong><small>MATH 214 · 5:00 PM</small></div><div className="deadline"><span className="deadline-date blue-text">FRI, OCT 18</span><strong>Primary Source Analysis</strong><small>HIST 110 · 11:59 PM</small></div></section></aside> }

export function Dashboard({ onNavigate }: { onNavigate?: (item: string) => void }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeNav, setActiveNav] = useState('Home')
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  const [data, setData] = useState<DashboardData | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { fetchDashboard().then(setData).catch(error => setError(error instanceof Error ? error.message : 'Unable to load dashboard')) }, [])
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2500) }
  const selectNav = (item: string) => { setActiveNav(item); showNotice(`${item} selected`); onNavigate?.(item) }
  if (error) return <div className="app-shell"><Header onMenu={() => setMenuOpen(true)} search={query} onSearch={setQuery} onAction={showNotice} /><div className="data-state"><strong>We couldn't load your semester</strong><p>{error}</p><button className="outline-btn" onClick={() => window.location.reload()}>Try again</button></div></div>
  if (!data) return <div className="app-shell"><Header onMenu={() => setMenuOpen(true)} search={query} onSearch={setQuery} onAction={showNotice} /><div className="data-state"><strong>Loading your semester...</strong><p>Getting your classes, deadlines, and events.</p></div></div>
  const scheduleItems = toScheduleItems(data); const assignmentItems = toAssignments(data); const eventItems = toEvents(data)
  return <div className="app-shell"><Header onMenu={() => setMenuOpen(true)} search={query} onSearch={setQuery} onAction={showNotice} /><Sidebar open={menuOpen} active={activeNav} onSelect={selectNav} close={() => setMenuOpen(false)} onAction={showNotice} /><main className="main-content"><div className="welcome"><div><span className="eyebrow">{data.semester.name.toUpperCase()}</span><h1>Good morning, Tom! <span>👋</span></h1><p>Here's what's happening with your semester.</p></div><button className="date-btn" onClick={() => showNotice('Showing today\'s schedule')}><CalendarDays size={16} /> Today <ChevronDown size={14} /></button></div>{query && <div className="search-status"><Search size={14} /> Showing matches for <strong>{query}</strong><button onClick={() => setQuery('')} aria-label="Clear search"><X size={14} /></button></div>}<div className="stats"><StatCard label="Classes Today" value={String(data.todaysClasses.length)} caption={data.todaysClasses.length ? 'Scheduled today' : 'Nothing scheduled'} tone="blue" icon={GraduationCap} /><StatCard label="Due Today" value={String(data.assignmentsDueToday.length)} caption={data.assignmentsDueToday.length ? data.assignmentsDueToday[0].title : 'Nothing due today'} tone="red" icon={FileText} /><StatCard label="Due This Week" value={String(data.upcomingAssignments.length)} caption="Upcoming assignments" tone="orange" icon={Clock3} /><StatCard label="Events This Week" value={String(data.clubEvents.length)} caption={data.clubEvents.length ? `Next: ${data.clubEvents[0].name}` : 'No upcoming events'} tone="purple" icon={CalendarDays} /></div><Schedule query={query} items={scheduleItems} /><div className="two-col"><Assignments query={query} items={assignmentItems} /><Events query={query} items={eventItems} onAction={showNotice} /></div><WeekGlance /></main><RightRail />{notice && <div className="toast" role="status">{notice}</div>}</div>
}
