import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './interactions.css'
import './phase2.css'
import './phase3.css'
import './brand.css'
import './advanced.css'
import './calendar-layout.css'
import './calendar-colors.css'
import './clickable-calendar.css'
import './calendar-create.css'
import './meeting-filter.css'
import './workspace-pages.css'
import './calendar-create-position.css'
import './calendar-class-layout.css'
import './calendar-create-final.css'
import './calendar-create-label.css'
import './calendar-filter-row.css'
import './calendar-event-type-colors.css'

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
